apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tools-appset
  namespace: argocd
spec:
    generators:
      - matrix:
          generators:
          - clusters: {}
          - git:
              repoURL: https://github.com/TanmayRao7/new-k8s-testing
              revision: master
              files:
              - path: clusterconfig/clusters/*/tools-list.yml
          - list:
              elements: []
              elementsYaml: "{{ .key.components | toJson }}"
    template:
      metadata:
        name: '{{ .name }}-{{.path.basename}}'
        namespace: argocd
      spec:
        project: default
        sources:
          repoURL: https://github.com/TanmayRao7/new-k8s-testing
          path: 'helm-charts/{{ .toolpath }}'
          targetRevision: master
          helm:
            valueFiles:
            - ../../helm-charts/secrets-store-csi-driver-provider-aws/values.yaml
            - ../../clusters/{{ .name }}/{{ .toolname }}-values.yaml
        destination:
          server: '{{.clusterName}}'
          namespace: '{{.path.basename}}'
        syncPolicy:
          automated: null
          syncOptions:
            - CreateNamespace=true
