apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tools-appset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
        - git:
            repoURL: https://github.com/TanmayRao7/new-k8s-testing.git
            revision: master
            files:
            - path: clusters/dev/cluster.yml
        - list:
            elements: []
            elementsYaml: "{{ .key.components | toJson }}"
  template:
    metadata:
      name: '{{ .name }}-{{ .toolname }}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/TanmayRao7/new-k8s-testing.git
        path: 'argocd/tools/{{ .toolpath }}'
        targetRevision: master
        helm:
          valueFiles:
          - ../../helm-charts/secrets-store-csi-driver-provider-aws/values.yaml
          - ../../clusters/{{ .name }}/{{ .toolname }}-values.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true