apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.name }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.region }}
    objects: |
{{ .Values.objects | indent 6 }}
